# Base Image 
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3.9
# Working directory inside app
WORKDIR /app
COPY . /app
# Install app dependecy 
RUN apt-get install python3-pip && pip3 install --upgrade pip
RUN PYTHONPATH=/usr/bin/python pip3 install -r requirements.txt
#Expose Nginx Port
EXPOSE 5000
#Start NginxService 
ENTRYPOINT ["python"]
CMD ["app.py"]
