# Base Image 
FROM python:3.8
# Working directory inside app
WORKDIR /app
COPY . /app
# Install app dependecy 
RUN pip install -r requirements.txt
#Expose Nginx Port
EXPOSE 5000
#Start NginxService 
ENTRYPOINT ["python"]
CMD ["app.py"]
