# Base Image 
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3.9
# Working directory inside app
WORKDIR /main
COPY . /main
# Install app dependecy 
RUN apt-get install -y python3-pip && pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
#Expose Nginx Port
EXPOSE 5000
#Start NginxService 
ENTRYPOINT ["bash","entrypoint.prod.sh"]
CMD ["python3", "app.py"]